commerce:
  gateways:
    82ebbe07-07ee-45bd-aaf2-a23c3a7676e3:
      handle: dummy
      isFrontendEnabled: true
      name: Dummy
      paymentType: purchase
      sortOrder: null
      type: craft\commerce\gateways\Dummy
    d408fbc3-daba-4531-8017-32de7a0c2a08:
      handle: payflow
      isFrontendEnabled: true
      name: Payflow
      paymentType: purchase
      settings:
        password: VA3YWZAXQTLRVP9H
        signature: AXO5VjTGOQS31ArS33xAv2bYSC50AdEbE6XYi2qo-UjiRZ-UDiSmG9Ff
        testMode: '1'
        user: autobell+1_api1.union.co
      sortOrder: null
      type: unionco\payflow\gateways\PayflowPro
  orderStatuses:
    4b4ab9e0-5a66-42dd-ae42-e4f51277acfa:
      color: green
      default: true
      handle: new
      name: New
      sortOrder: null
    a6b88db5-20b5-438c-a0f5-6df7c0fea1ae:
      color: blue
      default: false
      handle: shipped
      name: Shipped
      sortOrder: null
  productTypes:
    4829e3f0-5ce2-4b47-b578-7fddd337c4e0:
      descriptionFormat: ''
      handle: clothing
      hasDimensions: true
      hasVariantTitleField: false
      hasVariants: false
      name: Clothing
      siteSettings:
        8c671faa-294d-42c3-b5ca-2e12065870df:
          hasUrls: true
          template: shop/products/_product
          uriFormat: 'shop/products/{slug}'
      skuFormat: ''
      titleFormat: '{product.title}'
dateModified: 1556815313
email:
  fromEmail: abry.rath@Union.co
  fromName: Sandbox
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  59d31bcd-b077-4966-a85f-5e915c054a7c:
    name: Common
  928479c4-35b5-4539-a506-eb8e7f62f3be:
    name: EntryTypes
fields:
  7612361e-2859-4585-9f99-acfcee5cf7f8:
    contentColumnType: text
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
    handle: googlePlace
    instructions: ''
    name: 'Google Place'
    searchable: true
    settings:
      columnType: text
      mapCenter: 'Charlotte, NC'
      placeId: ''
    translationKeyFormat: null
    translationMethod: none
    type: unionco\googleservices\fields\GooglePlacesField
  df151ddf-8ad6-4e9d-b5bb-27c7d1fde5d1:
    contentColumnType: string
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
    handle: simpleMap
    instructions: ''
    name: 'Simple Map'
    searchable: true
    settings:
      boundary: '""'
      boundaryRestrictionNELat: ''
      boundaryRestrictionNELng: ''
      boundaryRestrictionSWLat: ''
      boundaryRestrictionSWLng: ''
      countryRestriction: ''
      height: '400'
      hideLatLng: '1'
      hideMap: ''
      lat: '51.272154'
      lng: '0.514951'
      typeRestriction: ''
      zoom: '15'
    translationKeyFormat: null
    translationMethod: none
    type: ether\simplemap\fields\MapField
  83681ac1-cb74-47ed-b9c2-e3791fb2dac6:
    name: 'Entry Types'
    handle: entryTypes
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: unionco\relatedentrytypes\fields\RelatedEntryTypesField
    settings:
      sections:
        - 'section:3634776b-6b68-4e15-96a9-f0f3f42e1951'
        - 'section:ce0b57ee-6dff-4d80-aa5a-d8381ba9323f'
      entryTypes:
        - '3'
        - '6'
        - '7'
      sources:
        - 'section:3634776b-6b68-4e15-96a9-f0f3f42e1951'
        - 'section:ce0b57ee-6dff-4d80-aa5a-d8381ba9323f'
      source: null
      targetSiteId: null
      viewMode: null
      limit: ''
      selectionLabel: ''
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 928479c4-35b5-4539-a506-eb8e7f62f3be
plugins:
  commerce:
    edition: lite
    enabled: false
    schemaVersion: 2.1.02
  commerce-payflow:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  geolocation:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
    settings:
      provider: ipstack
      providerSettings:
        googlemaps:
          apiKey: $GOOGLE_MAPS_API_KEY
        ipstack:
          accessKey: $IPSTACK_API_KEY
      providers:
        googlemaps:
          label: 'Google Maps'
          value: googlemaps
        ipstack:
          label: IPStack
          value: ipstack
  google-services:
    edition: standard
    enabled: false
    schemaVersion: 0.0.1
  import:
    edition: standard
    enabled: false
    schemaVersion: 0.0.1
  related-entry-types:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  simplemap:
    edition: standard
    enabled: false
    schemaVersion: 3.0.0
    settings:
      apiKey: AIzaSyDEdH_mOHQGM5zr1DoqnwUOxmN9B_HR3Rc
      unrestrictedApiKey: ''
  sync-db:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  3634776b-6b68-4e15-96a9-f0f3f42e1951:
    enableVersioning: true
    entryTypes:
      3161ab1f-5ff0-4065-a2d8-a262850e824d:
        fieldLayouts:
          cab8f0e2-d805-4f19-94db-04ed9cbe950e:
            tabs:
              -
                fields:
                  df151ddf-8ad6-4e9d-b5bb-27c7d1fde5d1:
                    required: false
                    sortOrder: 1
                name: Common
                sortOrder: 1
        handle: simpleMapLocation
        hasTitleField: true
        name: 'Simple Map Location'
        sortOrder: 2
        titleFormat: ''
        titleLabel: Title
      cc1c8567-2437-4075-b152-3614050c9589:
        fieldLayouts:
          a536b469-fa0e-4d24-bf1c-75b7326bca9d:
            tabs:
              -
                fields:
                  7612361e-2859-4585-9f99-acfcee5cf7f8:
                    required: false
                    sortOrder: 1
                name: Common
                sortOrder: 1
        handle: locations
        hasTitleField: true
        name: Locations
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: locations
    name: Locations
    propagateEntries: true
    siteSettings:
      8c671faa-294d-42c3-b5ca-2e12065870df:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'locations/{slug}'
    type: channel
  5e4fb093-81f2-4de3-9287-349052b1bfaa:
    enableVersioning: true
    entryTypes:
      38e3c2db-4415-41eb-b05c-e51501b140c5:
        name: Home
        handle: home
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          d441a8eb-66a4-469a-82fe-d9e10ebfb476:
            tabs:
              -
                name: EntryTypes
                sortOrder: 1
                fields:
                  83681ac1-cb74-47ed-b9c2-e3791fb2dac6:
                    required: false
                    sortOrder: 1
    handle: home
    name: Home
    propagateEntries: true
    siteSettings:
      8c671faa-294d-42c3-b5ca-2e12065870df:
        enabledByDefault: true
        hasUrls: true
        template: home/_entry
        uriFormat: __home__
    type: single
  ce0b57ee-6dff-4d80-aa5a-d8381ba9323f:
    enableVersioning: true
    entryTypes:
      26bb00d6-9836-4aa3-951c-b865a774468b:
        handle: contentDetail
        hasTitleField: true
        name: 'Content Detail'
        sortOrder: 2
        titleFormat: ''
        titleLabel: Title
      4849c6bf-6640-45f4-b843-0a182180e6c6:
        handle: faq
        hasTitleField: true
        name: FAQ
        sortOrder: 4
        titleFormat: ''
        titleLabel: Title
      78be31ea-f23e-49fa-98e6-f23f0f7a5cdf:
        handle: blog
        hasTitleField: true
        name: Blog
        sortOrder: 3
        titleFormat: ''
        titleLabel: Title
      a6f9e7a1-c59b-4490-9bc4-933799fb2960:
        handle: twoColumn
        hasTitleField: true
        name: 'Two Column'
        sortOrder: 5
        titleFormat: ''
        titleLabel: Title
    handle: pages
    name: Pages
    propagateEntries: true
    siteSettings:
      8c671faa-294d-42c3-b5ca-2e12065870df:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'pages/{slug}'
    type: channel
siteGroups:
  2c4afbfc-22ff-4aba-a8c9-a2f6896526a9:
    name: Sandbox
sites:
  8c671faa-294d-42c3-b5ca-2e12065870df:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Sandbox
    primary: true
    siteGroup: 2c4afbfc-22ff-4aba-a8c9-a2f6896526a9
    sortOrder: 1
system:
  edition: pro
  live: true
  name: Sandbox
  schemaVersion: 3.1.26
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
