categoryGroups:
  f7ec6621-99e1-42bd-8ce6-43bc3e0505f2:
    name: 'Article Type'
    handle: articleType
    structure:
      uid: 6f64799b-f643-4f60-9e20-61fb2bae037b
      maxLevels: null
    siteSettings:
      0c1b2059-4d4f-408d-b68b-5f012aa4ce23:
        hasUrls: false
        uriFormat: null
        template: null
dateModified: 1568990496
email:
  fromEmail: abry.rath@union.co
  fromName: Sandbox
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  a5811ad3-b965-4f2e-b27e-3ad6d6a32f89:
    name: Common
fields:
  5f616c3c-391c-410f-827a-922ebdb6f483:
    name: 'News Tags'
    handle: newsTags
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Tags
    settings:
      allowMultipleSources: false
      allowLimit: false
      sources: '*'
      source: 'taggroup:55d32ba1-4c24-4abb-b923-77980f536f40'
      targetSiteId: null
      viewMode: null
      limit: null
      selectionLabel: ''
      localizeRelations: ''
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: a5811ad3-b965-4f2e-b27e-3ad6d6a32f89
  9134083e-7bce-44f5-b4a7-c020ed944426:
    name: 'Map Location'
    handle: mapLocation
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: ether\simplemap\fields\MapField
    settings:
      lat: 51.272154
      lng: 0.514951
      zoom: 15
      minZoom: '3'
      maxZoom: '18'
      country: null
      hideSearch: ''
      hideMap: ''
      hideAddress: ''
      showLatLng: ''
      hideLatLng: null
      height: null
      countryRestriction: null
      typeRestriction: null
      boundaryRestrictionNELat: null
      boundaryRestrictionNELng: null
      boundaryRestrictionSWLat: null
      boundaryRestrictionSWLng: null
      boundary: '""'
    contentColumnType: text
    fieldGroup: a5811ad3-b965-4f2e-b27e-3ad6d6a32f89
  f93887bd-de0e-419a-91a7-4d8c40a59cc3:
    name: 'Article Type'
    handle: articleType
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Categories
    settings:
      allowLimit: false
      allowMultipleSources: false
      branchLimit: ''
      sources: '*'
      source: 'group:f7ec6621-99e1-42bd-8ce6-43bc3e0505f2'
      targetSiteId: null
      viewMode: null
      limit: null
      selectionLabel: ''
      localizeRelations: ''
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: a5811ad3-b965-4f2e-b27e-3ad6d6a32f89
plugins:
  autosuggest:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  simplemap:
    edition: standard
    enabled: true
    schemaVersion: 3.4.2
  geolocation:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
    settings:
      providers: null
      provider: ipstack
      providerSettings:
        ipstack:
          accessKey: $IPSTACK_API_KEY
        googlemaps:
          apiKey: ''
      ipOverride:
        row1:
          - 127.0.0.1
          - '35.22708'
          - '-80.84'
  coachmarks:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
sections:
  2f5c25c1-58a7-4d8d-8822-b1ca40adf6b7:
    name: Home
    handle: home
    type: single
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      0c1b2059-4d4f-408d-b68b-5f012aa4ce23:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: home/_entry
    entryTypes:
      57fa6464-f130-4390-aa35-1f54cfe3c0a9:
        name: Home
        handle: home
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  66d537e4-df2d-4ff3-8994-06939f48c45a:
    name: Stores
    handle: stores
    type: channel
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      0c1b2059-4d4f-408d-b68b-5f012aa4ce23:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'stores/{slug}'
        template: ''
    entryTypes:
      4ade6b2e-1a0d-445a-bd67-9b311f2e7386:
        name: Stores
        handle: stores
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          4aaeab43-a1dd-4a53-814d-64eeb00a1836:
            tabs:
              -
                name: 'Tab 1'
                sortOrder: 1
                fields:
                  9134083e-7bce-44f5-b4a7-c020ed944426:
                    required: false
                    sortOrder: 1
  66ed3676-3443-464c-87b5-d316bc57c87f:
    name: Locations
    handle: locations
    type: channel
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      0c1b2059-4d4f-408d-b68b-5f012aa4ce23:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'locations/{slug}'
        template: ''
    entryTypes:
      f2663fd6-3d20-4be9-9b4b-07ea58a6d61c:
        name: Locations
        handle: locations
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          2758974d-faa0-4a8d-91c6-b7b5b3765ead:
            tabs:
              -
                name: 'Tab 1'
                sortOrder: 1
                fields:
                  9134083e-7bce-44f5-b4a7-c020ed944426:
                    required: false
                    sortOrder: 2
  dde9fb28-7ca2-45b8-9e4f-921d74f5d46d:
    name: 'News & Events'
    handle: newsEvents
    type: channel
    enableVersioning: true
    propagationMethod: all
    siteSettings:
      0c1b2059-4d4f-408d-b68b-5f012aa4ce23:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'news-events/{slug}'
        template: ''
    entryTypes:
      97c79413-aa07-4951-9f7a-ebccaf6d9668:
        name: News
        handle: news
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          3af30485-b45b-4367-bc16-9b553089651a:
            tabs:
              -
                name: Common
                sortOrder: 1
                fields:
                  5f616c3c-391c-410f-827a-922ebdb6f483:
                    required: false
                    sortOrder: 1
                  f93887bd-de0e-419a-91a7-4d8c40a59cc3:
                    required: false
                    sortOrder: 2
      edad2fc3-f5b2-49be-82ca-d8e17c4614b4:
        name: Events
        handle: events
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 2
        fieldLayouts:
          d9b2bb51-247b-4137-a9bf-98c7f1965832:
            tabs:
              -
                name: Common
                sortOrder: 1
                fields:
                  5f616c3c-391c-410f-827a-922ebdb6f483:
                    required: false
                    sortOrder: 1
siteGroups:
  2e488dfc-a485-4901-9885-4bd62ba7bd0c:
    name: Sandbox
sites:
  0c1b2059-4d4f-408d-b68b-5f012aa4ce23:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Sandbox
    primary: true
    siteGroup: 2e488dfc-a485-4901-9885-4bd62ba7bd0c
    sortOrder: 1
system:
  edition: solo
  name: Sandbox
  live: true
  schemaVersion: 3.3.3
  timeZone: America/Los_Angeles
tagGroups:
  55d32ba1-4c24-4abb-b923-77980f536f40:
    name: News
    handle: news
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
