commerce:
  gateways:
    82ebbe07-07ee-45bd-aaf2-a23c3a7676e3:
      handle: dummy
      isFrontendEnabled: true
      name: Dummy
      paymentType: purchase
      sortOrder: null
      type: craft\commerce\gateways\Dummy
    d408fbc3-daba-4531-8017-32de7a0c2a08:
      handle: payflow
      isFrontendEnabled: true
      name: Payflow
      paymentType: purchase
      settings:
        password: VA3YWZAXQTLRVP9H
        signature: AXO5VjTGOQS31ArS33xAv2bYSC50AdEbE6XYi2qo-UjiRZ-UDiSmG9Ff
        testMode: '1'
        user: autobell+1_api1.union.co
      sortOrder: null
      type: unionco\payflow\gateways\PayflowPro
  orderStatuses:
    4b4ab9e0-5a66-42dd-ae42-e4f51277acfa:
      color: green
      default: true
      handle: new
      name: New
      sortOrder: null
    a6b88db5-20b5-438c-a0f5-6df7c0fea1ae:
      color: blue
      default: false
      handle: shipped
      name: Shipped
      sortOrder: null
  productTypes:
    4829e3f0-5ce2-4b47-b578-7fddd337c4e0:
      descriptionFormat: ''
      handle: clothing
      hasDimensions: true
      hasVariantTitleField: false
      hasVariants: false
      name: Clothing
      siteSettings:
        8c671faa-294d-42c3-b5ca-2e12065870df:
          hasUrls: true
          template: shop/products/_product
          uriFormat: 'shop/products/{slug}'
      skuFormat: ''
      titleFormat: '{product.title}'
dateModified: 1567958223
email:
  fromEmail: abry.rath@Union.co
  fromName: Sandbox
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  59d31bcd-b077-4966-a85f-5e915c054a7c:
    name: Common
  928479c4-35b5-4539-a506-eb8e7f62f3be:
    name: EntryTypes
fields:
  055788a4-5c1d-47ff-8d5e-4d360bd9b9cc:
    name: Locations
    handle: locations
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Matrix
    settings:
      minBlocks: ''
      maxBlocks: ''
      contentTable: '{{%matrixcontent_locations}}'
      localizeBlocks: false
    contentColumnType: string
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
  2ee777f2-c22c-4cfa-8df1-816b47e39fc6:
    name: 'Google Coords'
    handle: googleCoords
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: unionco\geolocation\fields\CoordinatesField
    settings:
      showMap: '1'
      mapProvider: google
      apiKey: $GOOGLE_MAPS_API_KEY
      columnType: text
    contentColumnType: text
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
  3cd0d1a3-8dd5-4b61-8910-e0809df6d6d9:
    name: 'Matrix With Geolocation'
    handle: matrixWithGeolocation
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Matrix
    settings:
      minBlocks: ''
      maxBlocks: ''
      contentTable: '{{%matrixcontent_matrixwithgeolocation}}'
      localizeBlocks: false
    contentColumnType: string
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
  4b17ed91-cdab-41ab-b06b-5360a1f81f91:
    name: 'Mapbox Coords'
    handle: mapboxCoords
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: unionco\geolocation\fields\CoordinatesField
    settings:
      showMap: '1'
      mapProvider: mapbox
      apiKey: $MAPBOX_API_TOKEN
      columnType: text
    contentColumnType: text
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
  5ca43528-1646-42ae-93fb-8ac80f375761:
    name: RET
    handle: ret
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: unionco\relatedentrytypes\fields\RelatedEntryTypesField
    settings:
      sections:
        - db8a903d-8886-4adf-af23-649a07d69993
      entryTypes:
        - '4'
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: null
      limit: ''
      selectionLabel: ''
      localizeRelations: false
      validateRelatedElements: false
    contentColumnType: string
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
  7612361e-2859-4585-9f99-acfcee5cf7f8:
    contentColumnType: text
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
    handle: googlePlace
    instructions: ''
    name: 'Google Place'
    searchable: true
    settings:
      columnType: text
      mapCenter: 'Charlotte, NC'
      placeId: ''
    translationKeyFormat: null
    translationMethod: none
    type: unionco\googleservices\fields\GooglePlacesField
  83681ac1-cb74-47ed-b9c2-e3791fb2dac6:
    name: 'Entry Types'
    handle: entryTypes
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: unionco\relatedentrytypes\fields\RelatedEntryTypesField
    settings:
      sections:
        - 'section:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'section:452e7866-2c9e-40ae-8467-88a339b65857'
      entryTypes:
        - '2'
        - '5'
      sources:
        - 'section:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'section:452e7866-2c9e-40ae-8467-88a339b65857'
      source: null
      targetSiteId: null
      viewMode: null
      limit: ''
      selectionLabel: ''
      localizeRelations: false
    contentColumnType: string
    fieldGroup: 928479c4-35b5-4539-a506-eb8e7f62f3be
  df151ddf-8ad6-4e9d-b5bb-27c7d1fde5d1:
    contentColumnType: string
    fieldGroup: 59d31bcd-b077-4966-a85f-5e915c054a7c
    handle: simpleMap
    instructions: ''
    name: 'Simple Map'
    searchable: true
    settings:
      boundary: '""'
      boundaryRestrictionNELat: ''
      boundaryRestrictionNELng: ''
      boundaryRestrictionSWLat: ''
      boundaryRestrictionSWLng: ''
      countryRestriction: ''
      height: '400'
      hideLatLng: '1'
      hideMap: ''
      lat: '51.272154'
      lng: '0.514951'
      typeRestriction: ''
      zoom: '15'
    translationKeyFormat: null
    translationMethod: none
    type: ether\simplemap\fields\MapField
matrixBlockTypes:
  2f80e8be-2133-4577-a6a7-12224eee3a5b:
    field: 3cd0d1a3-8dd5-4b61-8910-e0809df6d6d9
    name: Location
    handle: location
    sortOrder: 1
    fields:
      9f6b48fe-a04a-4394-b983-e17e23acb67d:
        name: 'Test Text'
        handle: testText
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\PlainText
        settings:
          placeholder: ''
          code: ''
          multiline: ''
          initialRows: '4'
          charLimit: ''
          columnType: text
        contentColumnType: text
        fieldGroup: null
    fieldLayouts:
      edfcb0b3-ec64-4ca8-8dbe-eda8bd102277:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              9f6b48fe-a04a-4394-b983-e17e23acb67d:
                required: false
                sortOrder: 1
  e0b1fb64-74cd-4999-a54c-49fa52922e79:
    field: 055788a4-5c1d-47ff-8d5e-4d360bd9b9cc
    name: testBlock
    handle: testblock
    sortOrder: 1
    fields:
      5e48e042-5937-471c-b36c-43e6292b5a07:
        name: testField2
        handle: testfield2
        instructions: ''
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: unionco\relatedentrytypes\fields\RelatedEntryTypesField
        settings:
          sections: null
          entryTypes:
            - '2'
            - '3'
            - '5'
          sources:
            - 'section:452e7866-2c9e-40ae-8467-88a339b65857'
          source: null
          targetSiteId: null
          viewMode: null
          limit: ''
          selectionLabel: ''
          localizeRelations: false
        contentColumnType: string
        fieldGroup: null
      9d4201b1-f4ab-410d-9c3d-977e027251e4:
        name: testField
        handle: testfield
        instructions: ''
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: unionco\relatedentrytypes\fields\RelatedEntryTypesField
        settings:
          sections: null
          entryTypes:
            - '2'
            - '3'
            - '6'
          sources:
            - 'section:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
            - 'section:452e7866-2c9e-40ae-8467-88a339b65857'
          source: null
          targetSiteId: null
          viewMode: null
          limit: ''
          selectionLabel: ''
          localizeRelations: false
        contentColumnType: string
        fieldGroup: null
    fieldLayouts:
      446d4b9f-05b2-4d14-83c5-439a07ccf776:
        tabs:
          -
            name: Content
            sortOrder: 1
            fields:
              5e48e042-5937-471c-b36c-43e6292b5a07:
                required: false
                sortOrder: 2
              9d4201b1-f4ab-410d-9c3d-977e027251e4:
                required: false
                sortOrder: 1
plugins:
  commerce:
    edition: lite
    enabled: false
    schemaVersion: 2.1.02
  commerce-payflow:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  geolocation:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
    settings:
      provider: ipstack
      providerSettings:
        googlemaps:
          apiKey: $GOOGLE_MAPS_API_KEY
        ipstack:
          accessKey: $IPSTACK_API_KEY
      providers:
        googlemaps:
          label: 'Google Maps'
          value: googlemaps
        ipstack:
          label: IPStack
          value: ipstack
  google-services:
    edition: standard
    enabled: false
    schemaVersion: 0.0.1
  import:
    edition: standard
    enabled: false
    schemaVersion: 0.0.1
  simplemap:
    edition: standard
    enabled: false
    schemaVersion: 3.0.0
    settings:
      apiKey: AIzaSyDEdH_mOHQGM5zr1DoqnwUOxmN9B_HR3Rc
      unrestrictedApiKey: ''
  sync-db:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
    settings:
      skipTables:
        - craft_templatecaches
      environments:
        production:
          username: abry
          host: abryrath.com
          root: /home/abry/Sites/craft3-sandbox/
          backupDirectory: /home/abry/Sites/craft3-sandbox/storage/backups/databases/
          port: 22
          phpPath: /usr/bin/php
          mysqlDumpPath: /usr/bin/mysqldump
          environment: production
          verbosity: 32
        staging:
          username: user
          host: staging.example.com
          root: /path/to/project/
          backupDirectory: /path/to/project/storage/backups/databases/
          port: 22
          phpPath: /usr/local/bin/php
          mysqlDumpPath: /usr/bin/mysqldump
          environment: staging
          verbosity: 128
  related-entry-types:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  coacher:
    edition: standard
    enabled: false
    schemaVersion: 0.0.1
  coachmarks:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
sections:
  3634776b-6b68-4e15-96a9-f0f3f42e1951:
    enableVersioning: true
    entryTypes:
      3161ab1f-5ff0-4065-a2d8-a262850e824d:
        fieldLayouts:
          cab8f0e2-d805-4f19-94db-04ed9cbe950e:
            tabs:
              -
                fields:
                  df151ddf-8ad6-4e9d-b5bb-27c7d1fde5d1:
                    required: false
                    sortOrder: 1
                name: Common
                sortOrder: 1
        handle: simpleMapLocation
        hasTitleField: true
        name: 'Simple Map Location'
        sortOrder: 2
        titleFormat: ''
        titleLabel: Title
      cc1c8567-2437-4075-b152-3614050c9589:
        fieldLayouts:
          a536b469-fa0e-4d24-bf1c-75b7326bca9d:
            tabs:
              -
                fields:
                  7612361e-2859-4585-9f99-acfcee5cf7f8:
                    required: false
                    sortOrder: 1
                name: Common
                sortOrder: 1
        handle: locations
        hasTitleField: true
        name: Locations
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: locations
    name: Locations
    siteSettings:
      8c671faa-294d-42c3-b5ca-2e12065870df:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'locations/{slug}'
    type: channel
    propagationMethod: all
  3beefca8-6a9f-4ca0-9e00-c673cf6cd138:
    name: Locations
    handle: locations
    type: channel
    enableVersioning: true
    siteSettings:
      8c671faa-294d-42c3-b5ca-2e12065870df:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'locations/{slug}'
        template: locations/_entry
    entryTypes:
      3425efc9-9938-4b0f-aba5-6510591b5076:
        name: GoogleLocationTest
        handle: locations
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          f2aea089-a89e-4e66-ba8e-a7749f842426:
            tabs:
              -
                name: 'Tab 1'
                sortOrder: 1
                fields:
                  2ee777f2-c22c-4cfa-8df1-816b47e39fc6:
                    required: false
                    sortOrder: 1
      abf888ee-973f-4edf-a9f6-675a1d6dc92c:
        name: MapBoxTest
        handle: test
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 2
        fieldLayouts:
          81ed2134-b2be-4c52-a7e4-f228f545ef5c:
            tabs:
              -
                name: 'Tab 1'
                sortOrder: 1
                fields:
                  4b17ed91-cdab-41ab-b06b-5360a1f81f91:
                    required: false
                    sortOrder: 1
    propagationMethod: all
  452e7866-2c9e-40ae-8467-88a339b65857:
    name: Pages
    handle: pages
    type: channel
    enableVersioning: true
    siteSettings:
      8c671faa-294d-42c3-b5ca-2e12065870df:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'pages/{slug}'
        template: ''
    entryTypes:
      6133e354-ef54-4736-bc28-cca2702bb9d3:
        name: Pages
        handle: pages
        hasTitleField: true
        titleLabel: Title
        titleFormat: null
        sortOrder: 1
      897f759e-efeb-4c51-9a9d-46be7e0ea7fb:
        name: Page1
        handle: page1
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 2
      d314c974-cb9b-4d11-99c2-dbe5930529b6:
        name: Page2
        handle: page2
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 3
    propagationMethod: all
  5e4fb093-81f2-4de3-9287-349052b1bfaa:
    enableVersioning: true
    entryTypes:
      38e3c2db-4415-41eb-b05c-e51501b140c5:
        name: Home
        handle: home
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          5a4a80a9-5fa2-4e9a-b9e5-746694e5390b:
            tabs:
              -
                name: EntryTypes
                sortOrder: 1
                fields:
                  83681ac1-cb74-47ed-b9c2-e3791fb2dac6:
                    required: false
                    sortOrder: 1
    handle: home
    name: Home
    siteSettings:
      8c671faa-294d-42c3-b5ca-2e12065870df:
        enabledByDefault: true
        hasUrls: true
        template: home/_entry
        uriFormat: __home__
    type: single
    propagationMethod: all
  ce0b57ee-6dff-4d80-aa5a-d8381ba9323f:
    enableVersioning: true
    entryTypes:
      26bb00d6-9836-4aa3-951c-b865a774468b:
        handle: contentDetail
        hasTitleField: true
        name: 'Content Detail'
        sortOrder: 2
        titleFormat: ''
        titleLabel: Title
      4849c6bf-6640-45f4-b843-0a182180e6c6:
        handle: faq
        hasTitleField: true
        name: FAQ
        sortOrder: 4
        titleFormat: ''
        titleLabel: Title
      78be31ea-f23e-49fa-98e6-f23f0f7a5cdf:
        handle: blog
        hasTitleField: true
        name: Blog
        sortOrder: 3
        titleFormat: ''
        titleLabel: Title
      a6f9e7a1-c59b-4490-9bc4-933799fb2960:
        handle: twoColumn
        hasTitleField: true
        name: 'Two Column'
        sortOrder: 5
        titleFormat: ''
        titleLabel: Title
    handle: pages
    name: Pages
    siteSettings:
      8c671faa-294d-42c3-b5ca-2e12065870df:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'pages/{slug}'
    type: channel
    propagationMethod: all
siteGroups:
  2c4afbfc-22ff-4aba-a8c9-a2f6896526a9:
    name: Sandbox
sites:
  8c671faa-294d-42c3-b5ca-2e12065870df:
    siteGroup: 2c4afbfc-22ff-4aba-a8c9-a2f6896526a9
    name: Sandbox
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: $DEFAULT_SITE_URL
    sortOrder: 1
    primary: true
system:
  edition: pro
  live: true
  name: Sandbox
  schemaVersion: 3.3.3
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
  groups:
    e125a90f-8ca0-429f-9506-6cdce2dbc18a:
      name: 'Pseudo Admin'
      handle: pseudoAdmin
      permissions:
        - accesssitewhensystemisoff
        - accesscp
        - customizesources
        - registerusers
        - moderateusers
        - assignuserpermissions
        - assignusergroups
        - administrateusers
        - editusers
        - deleteusers
        - 'publishentries:5e4fb093-81f2-4de3-9287-349052b1bfaa'
        - 'publishpeerentrydrafts:5e4fb093-81f2-4de3-9287-349052b1bfaa'
        - 'deletepeerentrydrafts:5e4fb093-81f2-4de3-9287-349052b1bfaa'
        - 'editpeerentrydrafts:5e4fb093-81f2-4de3-9287-349052b1bfaa'
        - 'editentries:5e4fb093-81f2-4de3-9287-349052b1bfaa'
        - 'createentries:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'publishentries:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'deleteentries:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'publishpeerentries:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'deletepeerentries:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'editpeerentries:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'publishpeerentrydrafts:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'deletepeerentrydrafts:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'editpeerentrydrafts:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'editentries:3beefca8-6a9f-4ca0-9e00-c673cf6cd138'
        - 'createentries:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'publishentries:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'deleteentries:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'publishpeerentries:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'deletepeerentries:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'editpeerentries:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'publishpeerentrydrafts:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'deletepeerentrydrafts:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'editpeerentrydrafts:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'editentries:452e7866-2c9e-40ae-8467-88a339b65857'
        - 'utility:updates'
        - 'utility:system-report'
        - 'utility:php-info'
        - 'utility:system-messages'
        - 'utility:search-indexes'
        - 'utility:clear-caches'
        - 'utility:deprecation-errors'
        - 'utility:db-backup'
        - 'utility:find-replace'
        - 'utility:migrations'
