environments:
  production:
    username: abry
    host: abryrath.com
    root: /home/abry/Sites/craft3-sandbox/
    backupDirectory: /home/abry/Sites/craft3-sandbox/storage/backups/databases/
    port: 22
    phpPath: /usr/bin/php
    mysqlDumpPath: /usr/bin/mysqldump
    environment: production
    verbosity: 32
  staging:
    username: user
    host: staging.example.com
    root: /path/to/project/
    backupDirectory: /path/to/project/storage/backups/databases/
    port: 22
    phpPath: /usr/local/bin/php
    mysqlDumpPath: /usr/bin/mysqldump
    environment: staging
    verbosity: 128
skipTables:
  - craft_templatecaches
